/*
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ru.iaie.reflex.ReflexRuntimeModule;
import ru.iaie.reflex.ReflexStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ReflexIdeSetup extends ReflexStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReflexRuntimeModule(), new ReflexIdeModule()));
	}
	
}
