/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.generator;

import com.google.inject.Inject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import ru.iaie.reflex.generator.R2CReflexGenerator;
import ru.iaie.reflex.generator.XMIReflexGenerator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ReflexGenerator extends AbstractGenerator {
  @Inject
  private R2CReflexGenerator r2cGen;
  
  @Inject
  private XMIReflexGenerator xmiGen;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.r2cGen.doGenerate(resource, fsa, context);
    this.xmiGen.doGenerate(resource, fsa, context);
  }
}
