/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.Const#getConstId <em>Const Id</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Const#getConstValue <em>Const Value</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getConst()
 * @model
 * @generated
 */
public interface Const extends EObject
{
  /**
   * Returns the value of the '<em><b>Const Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Id</em>' attribute.
   * @see #setConstId(String)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getConst_ConstId()
   * @model
   * @generated
   */
  String getConstId();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Const#getConstId <em>Const Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Id</em>' attribute.
   * @see #getConstId()
   * @generated
   */
  void setConstId(String value);

  /**
   * Returns the value of the '<em><b>Const Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Value</em>' containment reference.
   * @see #setConstValue(Expression)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getConst_ConstValue()
   * @model containment="true"
   * @generated
   */
  Expression getConstValue();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Const#getConstValue <em>Const Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Value</em>' containment reference.
   * @see #getConstValue()
   * @generated
   */
  void setConstValue(Expression value);

} // Const
