/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CType</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.CType#isSignSpec <em>Sign Spec</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getCType()
 * @model
 * @generated
 */
public interface CType extends ReflexType
{
  /**
   * Returns the value of the '<em><b>Sign Spec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign Spec</em>' attribute.
   * @see #setSignSpec(boolean)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getCType_SignSpec()
   * @model
   * @generated
   */
  boolean isSignSpec();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.CType#isSignSpec <em>Sign Spec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign Spec</em>' attribute.
   * @see #isSignSpec()
   * @generated
   */
  void setSignSpec(boolean value);

} // CType
