/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Body
{
} // Expression
