/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Physical Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.PhysicalVariable#getType <em>Type</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.PhysicalVariable#getPorts <em>Ports</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getPhysicalVariable()
 * @model
 * @generated
 */
public interface PhysicalVariable extends DeclaredVariable
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getPhysicalVariable_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.PhysicalVariable#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference list.
   * The list contents are of type {@link ru.iaie.reflex.reflex.RegisterPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference list.
   * @see ru.iaie.reflex.reflex.ReflexPackage#getPhysicalVariable_Ports()
   * @model containment="true"
   * @generated
   */
  EList<RegisterPort> getPorts();

} // PhysicalVariable
