/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getProcessVariable()
 * @model
 * @generated
 */
public interface ProcessVariable extends IdReference
{
} // ProcessVariable
