/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.UnaryExpression#getUnaryOp <em>Unary Op</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.UnaryExpression#getRest <em>Rest</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getUnaryExpression()
 * @model
 * @generated
 */
public interface UnaryExpression extends CastExpression
{
  /**
   * Returns the value of the '<em><b>Unary Op</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflex.reflex.UnaryOp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Op</em>' attribute.
   * @see ru.iaie.reflex.reflex.UnaryOp
   * @see #setUnaryOp(UnaryOp)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getUnaryExpression_UnaryOp()
   * @model
   * @generated
   */
  UnaryOp getUnaryOp();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.UnaryExpression#getUnaryOp <em>Unary Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Op</em>' attribute.
   * @see ru.iaie.reflex.reflex.UnaryOp
   * @see #getUnaryOp()
   * @generated
   */
  void setUnaryOp(UnaryOp value);

  /**
   * Returns the value of the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rest</em>' containment reference.
   * @see #setRest(CastExpression)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getUnaryExpression_Rest()
   * @model containment="true"
   * @generated
   */
  CastExpression getRest();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.UnaryExpression#getRest <em>Rest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rest</em>' containment reference.
   * @see #getRest()
   * @generated
   */
  void setRest(CastExpression value);

} // UnaryExpression
