/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.reflex.impl;

import java.lang.Integer;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ru.iaie.reflex.reflex.ReflexPackage;
import ru.iaie.reflex.reflex.Register;
import ru.iaie.reflex.reflex.RegisterType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Register</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.impl.RegisterImpl#getType <em>Type</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.impl.RegisterImpl#getName <em>Name</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.impl.RegisterImpl#getAddr1 <em>Addr1</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.impl.RegisterImpl#getAddr2 <em>Addr2</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.impl.RegisterImpl#getRegSize <em>Reg Size</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RegisterImpl extends MinimalEObjectImpl.Container implements Register
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final RegisterType TYPE_EDEFAULT = RegisterType.INPUT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected RegisterType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAddr1() <em>Addr1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddr1()
   * @generated
   * @ordered
   */
  protected ru.iaie.reflex.reflex.Integer addr1;

  /**
   * The cached value of the '{@link #getAddr2() <em>Addr2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddr2()
   * @generated
   * @ordered
   */
  protected ru.iaie.reflex.reflex.Integer addr2;

  /**
   * The default value of the '{@link #getRegSize() <em>Reg Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegSize()
   * @generated
   * @ordered
   */
  protected static final int REG_SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRegSize() <em>Reg Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegSize()
   * @generated
   * @ordered
   */
  protected int regSize = REG_SIZE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegisterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReflexPackage.Literals.REGISTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RegisterType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(RegisterType newType)
  {
    RegisterType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ru.iaie.reflex.reflex.Integer getAddr1()
  {
    return addr1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAddr1(ru.iaie.reflex.reflex.Integer newAddr1, NotificationChain msgs)
  {
    ru.iaie.reflex.reflex.Integer oldAddr1 = addr1;
    addr1 = newAddr1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__ADDR1, oldAddr1, newAddr1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAddr1(ru.iaie.reflex.reflex.Integer newAddr1)
  {
    if (newAddr1 != addr1)
    {
      NotificationChain msgs = null;
      if (addr1 != null)
        msgs = ((InternalEObject)addr1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReflexPackage.REGISTER__ADDR1, null, msgs);
      if (newAddr1 != null)
        msgs = ((InternalEObject)newAddr1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReflexPackage.REGISTER__ADDR1, null, msgs);
      msgs = basicSetAddr1(newAddr1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__ADDR1, newAddr1, newAddr1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ru.iaie.reflex.reflex.Integer getAddr2()
  {
    return addr2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAddr2(ru.iaie.reflex.reflex.Integer newAddr2, NotificationChain msgs)
  {
    ru.iaie.reflex.reflex.Integer oldAddr2 = addr2;
    addr2 = newAddr2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__ADDR2, oldAddr2, newAddr2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAddr2(ru.iaie.reflex.reflex.Integer newAddr2)
  {
    if (newAddr2 != addr2)
    {
      NotificationChain msgs = null;
      if (addr2 != null)
        msgs = ((InternalEObject)addr2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReflexPackage.REGISTER__ADDR2, null, msgs);
      if (newAddr2 != null)
        msgs = ((InternalEObject)newAddr2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReflexPackage.REGISTER__ADDR2, null, msgs);
      msgs = basicSetAddr2(newAddr2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__ADDR2, newAddr2, newAddr2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRegSize()
  {
    return regSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRegSize(int newRegSize)
  {
    int oldRegSize = regSize;
    regSize = newRegSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReflexPackage.REGISTER__REG_SIZE, oldRegSize, regSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ReflexPackage.REGISTER__ADDR1:
        return basicSetAddr1(null, msgs);
      case ReflexPackage.REGISTER__ADDR2:
        return basicSetAddr2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReflexPackage.REGISTER__TYPE:
        return getType();
      case ReflexPackage.REGISTER__NAME:
        return getName();
      case ReflexPackage.REGISTER__ADDR1:
        return getAddr1();
      case ReflexPackage.REGISTER__ADDR2:
        return getAddr2();
      case ReflexPackage.REGISTER__REG_SIZE:
        return getRegSize();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReflexPackage.REGISTER__TYPE:
        setType((RegisterType)newValue);
        return;
      case ReflexPackage.REGISTER__NAME:
        setName((String)newValue);
        return;
      case ReflexPackage.REGISTER__ADDR1:
        setAddr1((ru.iaie.reflex.reflex.Integer)newValue);
        return;
      case ReflexPackage.REGISTER__ADDR2:
        setAddr2((ru.iaie.reflex.reflex.Integer)newValue);
        return;
      case ReflexPackage.REGISTER__REG_SIZE:
        setRegSize((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReflexPackage.REGISTER__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case ReflexPackage.REGISTER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ReflexPackage.REGISTER__ADDR1:
        setAddr1((ru.iaie.reflex.reflex.Integer)null);
        return;
      case ReflexPackage.REGISTER__ADDR2:
        setAddr2((ru.iaie.reflex.reflex.Integer)null);
        return;
      case ReflexPackage.REGISTER__REG_SIZE:
        setRegSize(REG_SIZE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReflexPackage.REGISTER__TYPE:
        return type != TYPE_EDEFAULT;
      case ReflexPackage.REGISTER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ReflexPackage.REGISTER__ADDR1:
        return addr1 != null;
      case ReflexPackage.REGISTER__ADDR2:
        return addr2 != null;
      case ReflexPackage.REGISTER__REG_SIZE:
        return regSize != REG_SIZE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", name: ");
    result.append(name);
    result.append(", regSize: ");
    result.append(regSize);
    result.append(')');
    return result.toString();
  }

} //RegisterImpl
